
### create short url code
POST http://localhost:8000/api/short_url
Accept: application/json
Content-Type: application/json

{
    "og_url": "https://dongstudio.medium.com/"
}

### get og url
GET http://localhost:8000/api/short_url?short_url_code=XXXXXX
accept: application/json



